#!/usr/bin/env python3
"""Generate the placeholder UI art (icons + menu background) used by Ghumante.uss.

    python game/Tools/make_ui_art.py

Everything is drawn procedurally with Pillow (supersampled 4x, then downscaled), so the art is ours to
license and can be regenerated byte-for-byte. Final art replaces these PNGs under the same file names
(see docs/ASSET_MANIFEST.md). Requires Pillow >= 10 built with libraqm for the Devanagari coin glyph.
"""
from __future__ import annotations

import math
import random
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont, features

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "Assets" / "Ghumante" / "UI" / "Icons"
FONTS = ROOT / "Assets" / "Ghumante" / "UI" / "Fonts"
SS = 4          # supersampling factor
ICON = 128      # output icon size (displayed at 64-72 px, so 2x density)

OUTLINE = (106, 61, 16, 255)


def canvas(size: int = ICON) -> tuple[Image.Image, ImageDraw.ImageDraw, float]:
    img = Image.new("RGBA", (size * SS, size * SS), (0, 0, 0, 0))
    return img, ImageDraw.Draw(img), size * SS / 128.0


def save(img: Image.Image, name: str, size: int = ICON) -> None:
    out = img.resize((size, size), Image.LANCZOS)
    # PNG writer without timestamps/text chunks: identical bytes on every run.
    out.save(OUT / name, optimize=True)
    print("wrote", (OUT / name).relative_to(ROOT))


def poly_scaled(points, k):
    return [(x * k, y * k) for x, y in points]


def heart():
    img, d, k = canvas()
    pts = []
    for i in range(200):
        t = math.pi * 2 * i / 200
        x = 16 * math.sin(t) ** 3
        y = -(13 * math.cos(t) - 5 * math.cos(2 * t) - 2 * math.cos(3 * t) - math.cos(4 * t))
        pts.append((64 + x * 3.4, 62 + y * 3.4))
    d.polygon(poly_scaled(pts, k), fill=(232, 52, 64, 255), outline=OUTLINE, width=int(5 * k))
    d.ellipse(poly_scaled([(34, 30), (56, 50)], k), fill=(255, 255, 255, 150))
    save(img, "heart.png")


def star():
    img, d, k = canvas()
    pts = []
    for i in range(10):
        r = 58 if i % 2 == 0 else 26
        a = -math.pi / 2 + i * math.pi / 5
        pts.append((64 + r * math.cos(a), 68 + r * math.sin(a)))
    d.polygon(poly_scaled(pts, k), fill=(255, 205, 46, 255), outline=(199, 120, 10, 255), width=int(5 * k))
    d.ellipse(poly_scaled([(50, 36), (66, 52)], k), fill=(255, 255, 255, 160))
    save(img, "star.png")


def coin():
    img, d, k = canvas()
    d.ellipse(poly_scaled([(6, 6), (122, 122)], k), fill=(214, 140, 18, 255), outline=OUTLINE, width=int(4 * k))
    d.ellipse(poly_scaled([(16, 12), (112, 108)], k), fill=(255, 201, 46, 255))
    d.ellipse(poly_scaled([(26, 22), (102, 98)], k), outline=(214, 140, 18, 255), width=int(4 * k))
    if features.check("raqm"):
        font = ImageFont.truetype(str(FONTS / "Baloo2-ExtraBold.ttf"), int(58 * k), layout_engine=ImageFont.Layout.RAQM)
        text = "रु"  # रु, the Nepali rupee abbreviation
        box = d.textbbox((0, 0), text, font=font, language="ne")
        w, h = box[2] - box[0], box[3] - box[1]
        d.text((64 * k - w / 2 - box[0], 60 * k - h / 2 - box[1]), text, font=font, fill=(178, 105, 8, 255), language="ne")
    save(img, "coin.png")


def energy():
    img, d, k = canvas()
    bolt = [(74, 4), (24, 72), (58, 72), (46, 124), (104, 48), (68, 48), (86, 4)]
    d.polygon(poly_scaled(bolt, k), fill=(255, 214, 51, 255), outline=(199, 120, 10, 255), width=int(5 * k))
    save(img, "energy.png")


def gear():
    img, d, k = canvas()
    teeth = []
    n = 8
    for i in range(n * 4):
        a = i * 2 * math.pi / (n * 4)
        r = 58 if (i % 4) in (1, 2) else 44
        teeth.append((64 + r * math.cos(a), 64 + r * math.sin(a)))
    d.polygon(poly_scaled(teeth, k), fill=(140, 103, 65, 255), outline=OUTLINE, width=int(3 * k))
    d.ellipse(poly_scaled([(42, 42), (86, 86)], k), fill=(255, 246, 227, 255), outline=OUTLINE, width=int(3 * k))
    save(img, "gear.png")


def globe():
    img, d, k = canvas()
    d.ellipse(poly_scaled([(8, 8), (120, 120)], k), fill=(53, 194, 241, 255), outline=(23, 129, 191, 255), width=int(5 * k))
    for box in ([(36, 10), (92, 118)], [(56, 10), (72, 118)]):
        d.ellipse(poly_scaled(box, k), outline=(255, 255, 255, 220), width=int(4 * k))
    for y in (40, 64, 88):
        half = math.sqrt(max(0.0, 56 ** 2 - (y - 64) ** 2))
        d.line(poly_scaled([(64 - half, y), (64 + half, y)], k), fill=(255, 255, 255, 220), width=int(4 * k))
    save(img, "globe.png")


def back():
    img, d, k = canvas()
    arrow = [(14, 64), (62, 20), (62, 46), (114, 46), (114, 82), (62, 82), (62, 108)]
    d.polygon(poly_scaled(arrow, k), fill=(91, 55, 20, 255))
    save(img, "back.png")


def map_icon():
    img, d, k = canvas()
    panels = [
        ([(10, 24), (46, 12), (46, 104), (10, 116)], (255, 236, 179, 255)),
        ([(46, 12), (82, 24), (82, 116), (46, 104)], (255, 214, 120, 255)),
        ([(82, 24), (118, 12), (118, 104), (82, 116)], (255, 236, 179, 255)),
    ]
    for pts, col in panels:
        d.polygon(poly_scaled(pts, k), fill=col, outline=OUTLINE, width=int(4 * k))
    d.line(poly_scaled([(18, 90), (40, 60), (60, 74), (84, 44), (108, 52)], k), fill=(232, 52, 64, 255), width=int(6 * k))
    d.ellipse(poly_scaled([(100, 44), (116, 60)], k), fill=(232, 52, 64, 255))
    save(img, "map.png")


def background():
    w, h = 1280, 720
    W, H = w * 2, h * 2
    img = Image.new("RGBA", (W, H))
    d = ImageDraw.Draw(img)
    top, bottom = (127, 211, 247), (217, 243, 255)
    for y in range(H):
        t = y / (H - 1)
        d.line([(0, y), (W, y)], fill=tuple(int(top[i] + (bottom[i] - top[i]) * t) for i in range(3)) + (255,))
    rng = random.Random(1951)  # fixed seed: identical output on every run

    def ridge_line(base, amp, step):
        pts, x = [], 0
        while True:
            pts.append((x, base - amp * rng.uniform(0.15, 1.0)))
            if x >= W:
                return pts
            x = min(W, x + rng.randint(step // 2, step))

    def band(points, color):
        poly = [(0, H)] + points + [(W, H)]
        d.polygon(poly, fill=color)

    # Himalaya: sharp peaks, snow above a jagged snowline (mask = mountain AND above snowline).
    peaks = ridge_line(H * 0.60, 520, 260)
    mountain = Image.new("L", (W, H), 0)
    ImageDraw.Draw(mountain).polygon([(0, H)] + peaks + [(W, H)], fill=255)
    snowline = Image.new("L", (W, H), 0)
    sl = [(x, H * 0.60 - 300 + 40 * math.sin(x / 90.0) + rng.uniform(-20, 20)) for x in range(0, W + 60, 60)]
    ImageDraw.Draw(snowline).polygon([(0, 0)] + sl + [(W, 0)], fill=255)
    img.paste((150, 176, 214, 255), (0, 0), mountain)
    snow = Image.composite(mountain, Image.new("L", (W, H), 0), snowline)
    img.paste((255, 255, 255, 255), (0, 0), snow)
    # Shadowed faces: darken the right flank of each peak.
    shade = Image.new("L", (W, H), 0)
    sd = ImageDraw.Draw(shade)
    for (x0, y0), (x1, y1) in zip(peaks, peaks[1:]):
        if y0 < y1:  # descending to the right: shadow side
            sd.polygon([(x0, y0), (x1, y1), (x1, H), (x0 + (x1 - x0) * 0.4, H)], fill=60)
    shade = Image.composite(shade, Image.new("L", (W, H), 0), mountain)
    img.paste((40, 60, 110, 255), (0, 0), shade)

    d = ImageDraw.Draw(img)
    band(ridge_line(H * 0.74, 150, 300), (126, 200, 98, 255))   # middle hills
    band(ridge_line(H * 0.88, 80, 360), (86, 166, 62, 255))     # foreground terraces
    for cx, cy, s in ((300, 260, 1.0), (1700, 180, 1.3), (2250, 330, 0.8)):
        for dx, dy, r in ((0, 0, 60), (60, -20, 70), (130, 0, 55)):
            d.ellipse([cx + dx * s - r * s, cy + dy * s - r * s, cx + dx * s + r * s, cy + dy * s + r * s],
                      fill=(255, 255, 255, 235))
    img = img.filter(ImageFilter.GaussianBlur(1)).resize((w, h), Image.LANCZOS)
    img.convert("RGB").save(OUT / "background-himalaya.png", optimize=True)
    print("wrote", (OUT / "background-himalaya.png").relative_to(ROOT))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    heart()
    star()
    coin()
    energy()
    gear()
    globe()
    back()
    map_icon()
    background()


if __name__ == "__main__":
    main()
