#!/usr/bin/env python3
"""Generate the Devanagari TextSpike screen and its HarfBuzz reference images (ARCHITECTURE.md P3).

    python game/Tools/textspike.py           # regenerate
    python game/Tools/textspike.py --check   # exit 1 if the UXML is stale or a reference image is missing

Source of truth: game/Tools/textspike_cases.json (id, font, text, note).
Outputs (all under game/Assets/Ghumante/UI/):
    Screens/TextSpike.uxml                 the test screen, one row per case
    TextSpike/TextSpikeReference.uss       one .spike-ref--<id> class per case (image + size)
    TextSpike/Reference/<id>.png           the case rendered by HarfBuzz (Pillow + libraqm) with the
                                           SAME font file the UI uses, at 2x density

On device, every "Live" cell (UI Toolkit, Advanced Text Generator) must look like its "Reference" cell.
The reference is produced by HarfBuzz, the same shaping engine the Advanced Text Generator uses, so a
mismatch points at the Unity integration (generator not enabled, wrong font asset type, fallback font),
not at the font.

Requires Pillow >= 10 built with libraqm (features.check("raqm") must be True).
"""
from __future__ import annotations

import argparse
import io
import json
import re
import sys
import tempfile
import unicodedata
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, features

ROOT = Path(__file__).resolve().parents[1]
UI = ROOT / "Assets" / "Ghumante" / "UI"
CASES = Path(__file__).with_name("textspike_cases.json")
FONT_FILES = {"body": UI / "Fonts" / "Mukta-Regular.ttf", "display": UI / "Fonts" / "Baloo2-ExtraBold.ttf"}
INK = (91, 55, 20, 255)
DENSITY = 2          # reference PNGs are rendered at 2x the UI pixel size
WRAP_WIDTH_PX = 632  # UI pixels: .spike-live content width (660 - 2*10 padding) minus the label padding (2*4)
PAD_PX = 4


def esc(s: str) -> str:
    """XML attribute escaping; invisible joiners become numeric references so the source stays readable."""
    out = (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;"))
    return out.replace("‍", "&#x200D;").replace("‌", "&#x200C;")


def wrap(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.FreeTypeFont, max_w: int) -> list[str]:
    words, lines, cur = text.split(" "), [], ""
    for w in words:
        trial = w if not cur else cur + " " + w
        if draw.textlength(trial, font=font, language="ne") <= max_w or not cur:
            cur = trial
        else:
            lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


def render(case: dict, size_px: int) -> tuple[bytes, int, int]:
    font = ImageFont.truetype(str(FONT_FILES[case["font"]]), size_px * DENSITY, layout_engine=ImageFont.Layout.RAQM)
    scratch = ImageDraw.Draw(Image.new("RGBA", (8, 8)))
    lines = wrap(scratch, case["text"], font, WRAP_WIDTH_PX * DENSITY)
    ascent, descent = font.getmetrics()
    line_h = ascent + descent
    width = max(int(scratch.textlength(l, font=font, language="ne")) for l in lines) + 2 * PAD_PX * DENSITY
    height = line_h * len(lines) + 2 * PAD_PX * DENSITY
    # Round up to even pixels so the 1x size in USS is an integer.
    width += width % 2
    height += height % 2
    img = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    for i, line in enumerate(lines):
        d.text((PAD_PX * DENSITY, PAD_PX * DENSITY + i * line_h), line, font=font, fill=INK, language="ne")
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue(), width // DENSITY, height // DENSITY


def build(out_root: Path) -> dict[Path, bytes]:
    spec = json.loads(CASES.read_text(encoding="utf-8"))
    sizes = spec["font_size_px"]
    files: dict[Path, bytes] = {}
    uss = [
        "/* GENERATED by game/Tools/textspike.py from game/Tools/textspike_cases.json. Do not edit. */",
        "",
    ]
    rows = []
    for case in spec["cases"]:
        cid, text = case["id"], case["text"]
        if unicodedata.normalize("NFC", text) != text:
            raise SystemExit(f"case {cid}: text is not NFC")
        png, w, h = render(case, sizes[case["font"]])
        files[out_root / "TextSpike" / "Reference" / f"{cid}.png"] = png
        uss += [f".spike-ref--{cid} {{",
                f'    background-image: url("Reference/{cid}.png");',
                f"    width: {w}px;",
                f"    height: {h}px;",
                "}", ""]
        rows.append(f'''                <ui:VisualElement name="case-{cid}" class="spike-row">
                    <ui:VisualElement class="spike-meta">
                        <ui:Label class="spike-id" text="{esc(cid)}" />
                        <ui:Label class="spike-note" text="{esc(case["note"])}" />
                    </ui:VisualElement>
                    <ui:VisualElement class="spike-live">
                        <ui:Label name="sample-{cid}" class="spike-sample spike-sample--{case["font"]}" text="{esc(text)}" />
                    </ui:VisualElement>
                    <ui:VisualElement class="spike-ref-col">
                        <ui:VisualElement class="spike-ref spike-ref--{cid}" picking-mode="Ignore" />
                    </ui:VisualElement>
                </ui:VisualElement>''')
    files[out_root / "TextSpike" / "TextSpikeReference.uss"] = "\n".join(uss).encode("utf-8")
    uxml = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by game/Tools/textspike.py from game/Tools/textspike_cases.json. Do not edit by hand.
     Devanagari shaping spike (ARCHITECTURE.md P3): every Live cell must match its Reference cell. -->
<ui:UXML xmlns:ui="UnityEngine.UIElements" editor-extension-mode="False">
    <Style src="../Styles/Ghumante.uss" />
    <Style src="../TextSpike/TextSpike.uss" />
    <Style src="../TextSpike/TextSpikeReference.uss" />
    <ui:VisualElement name="text-spike" class="gh-root gh-screen">
        <ui:VisualElement class="gh-topbar">
            <ui:Button name="back-button" class="gh-icon-btn gh-icon-btn--small">
                <ui:VisualElement class="gh-icon gh-icon--small gh-icon--back" picking-mode="Ignore" />
            </ui:Button>
            <ui:VisualElement class="gh-ribbon gh-ribbon--small" picking-mode="Ignore">
                <ui:VisualElement class="gh-ribbon__tail gh-ribbon__tail--left" picking-mode="Ignore" />
                <ui:VisualElement class="gh-ribbon__tail gh-ribbon__tail--right" picking-mode="Ignore" />
                <ui:Label class="gh-ribbon__title" binding-path="spike.title" text="Devanagari text test" picking-mode="Ignore" />
            </ui:VisualElement>
            <!-- Keeps the ribbon centred between the back button and the right edge. -->
            <ui:VisualElement class="spike-topbar-spacer" picking-mode="Ignore" />
        </ui:VisualElement>
        <ui:VisualElement class="gh-panel spike-panel">
            <ui:Label name="device-info" class="spike-device-info" text="device info" />
            <ui:Label class="spike-instructions" binding-path="spike.instructions" text="Each live row must look like its reference image." />
            <ui:VisualElement class="spike-row spike-row--header">
                <ui:Label class="spike-meta spike-header" binding-path="spike.column.case" text="Case" />
                <ui:Label class="spike-live spike-header" binding-path="spike.column.live" text="Live (UI Toolkit)" />
                <ui:Label class="spike-ref-col spike-header" binding-path="spike.column.reference" text="Reference (HarfBuzz)" />
            </ui:VisualElement>
            <ui:ScrollView name="spike-list" class="spike-list" mode="Vertical" horizontal-scroller-visibility="Hidden">
{chr(10).join(rows)}
            </ui:ScrollView>
        </ui:VisualElement>
        <!-- Toggles live in a bottom bar so they sit in the thumb zone in portrait (ADR-017). -->
        <ui:VisualElement name="spike-toolbar" class="gh-bottombar spike-toolbar">
            <ui:Button name="toggle-language" class="gh-pill gh-pill--small gh-pill--cyan">
                <ui:VisualElement class="gh-pill__gloss" picking-mode="Ignore" />
                <ui:Label name="toggle-language-label" class="gh-pill__label" text="नेपाली" picking-mode="Ignore" />
            </ui:Button>
            <ui:Button name="toggle-generator" class="gh-pill gh-pill--small gh-pill--yellow">
                <ui:VisualElement class="gh-pill__gloss" picking-mode="Ignore" />
                <ui:Label name="toggle-generator-label" class="gh-pill__label" text="Shaping: Advanced" picking-mode="Ignore" />
            </ui:Button>
            <ui:Button name="toggle-numerals" class="gh-pill gh-pill--small gh-pill--green">
                <ui:VisualElement class="gh-pill__gloss" picking-mode="Ignore" />
                <ui:Label name="toggle-numerals-label" class="gh-pill__label" text="Numerals: ०१२" picking-mode="Ignore" />
            </ui:Button>
        </ui:VisualElement>
    </ui:VisualElement>
</ui:UXML>
'''
    files[out_root / "Screens" / "TextSpike.uxml"] = uxml.encode("utf-8")
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if generated files differ from the committed ones")
    args = parser.parse_args()
    if not features.check("raqm"):
        print("Pillow was built without libraqm: cannot shape Devanagari", file=sys.stderr)
        return 2
    files = build(UI)
    if args.check:
        # The UXML must match byte for byte. PNG pixels (and the sizes in the generated USS) depend on the
        # FreeType/HarfBuzz build inside Pillow, so for those only presence is checked.
        def stale_file(p: Path, data: bytes) -> bool:
            if not p.exists():
                return True
            if p.suffix == ".uxml":
                return p.read_bytes() != data
            if p.suffix == ".uss":
                current = p.read_text(encoding="utf-8")
                return any(f".spike-ref--{c} {{" not in current for c in re.findall(r"\.spike-ref--([\w-]+) \{", data.decode()))
            return False
        stale = [p for p, data in files.items() if stale_file(p, data)]
        refs = UI / "TextSpike" / "Reference"
        extra = [p for p in refs.glob("*.png") if p not in files] if refs.exists() else []
        for p in stale:
            print(f"out of date: {p.relative_to(ROOT)}")
        for p in extra:
            print(f"orphan: {p.relative_to(ROOT)}")
        if stale or extra:
            print("run: python game/Tools/textspike.py", file=sys.stderr)
            return 1
        print(f"TextSpike up to date ({len(files)} files)")
        return 0
    for p, data in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)
    refs = UI / "TextSpike" / "Reference"
    for p in refs.glob("*.png"):
        if p not in files:
            p.unlink()
    print(f"wrote {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
