using System;
using Ghumante.UI.Localization;
using UnityEngine;
using UnityEngine.UIElements;

namespace Ghumante.UI.Screens
{
    /// <summary>
    /// Presenter for <c>Screens/TextSpike.uxml</c>, the week-1 Devanagari shaping spike (ARCHITECTURE.md P3).
    /// The sample rows are static UXML generated by <c>game/Tools/textspike.py</c>; this class only wires
    /// the toolbar and prints the device facts that belong in the test report screenshot.
    /// </summary>
    public sealed class TextSpikeScreen : ScreenBase
    {
        /// <summary>USS class that switches the samples to the legacy (unshaped) text generator.</summary>
        public const string StandardGeneratorClass = "spike--standard";

        private readonly Label _languageLabel;
        private readonly Label _generatorLabel;
        private readonly Label _numeralsLabel;
        private readonly Label _deviceInfo;
        private bool _standardGenerator;

        public TextSpikeScreen(VisualElement root, Localizer localizer)
            : base(root, localizer)
        {
            _languageLabel = Required<Label>("toggle-language-label");
            _generatorLabel = Required<Label>("toggle-generator-label");
            _numeralsLabel = Required<Label>("toggle-numerals-label");
            _deviceInfo = Required<Label>("device-info");

            Required<Button>("back-button").clicked += () =>
            {
                Action handler = BackRequested;
                if (handler != null) handler();
            };
            Required<Button>("toggle-language").clicked += () =>
            {
                Action handler = LanguageToggleRequested;
                if (handler != null) handler();
            };
            Required<Button>("toggle-generator").clicked += ToggleGenerator;
            Required<Button>("toggle-numerals").clicked += () => Localizer.NativeNumerals = !Localizer.NativeNumerals;

            // Rotation, window resize and fold/unfold change Screen.width/height, which the device line
            // reports; GeometryChangedEvent on the styled root fires for all of them (ADR-017).
            StyledRoot.RegisterCallback<GeometryChangedEvent>(OnGeometryChanged);

            Refresh();
        }

        public override void Dispose()
        {
            StyledRoot.UnregisterCallback<GeometryChangedEvent>(OnGeometryChanged);
            base.Dispose();
        }

        public event Action BackRequested;
        public event Action LanguageToggleRequested;

        /// <summary>Number of sample rows (one per case in game/Tools/textspike_cases.json).</summary>
        public int SampleCount
        {
            get { return Root.Query<Label>(className: "spike-sample").ToList().Count; }
        }

        protected override void OnRefresh()
        {
            bool nepali = Localizer.Locale == Localizer.Nepali;
            // The button names the language you switch TO, in that language.
            _languageLabel.text = nepali ? "English" : "नेपाली";
            _generatorLabel.text = Localizer.Format(
                "spike.generator",
                Localizer.Get(_standardGenerator ? "spike.generator.standard" : "spike.generator.advanced"));
            _numeralsLabel.text = Localizer.Get(Localizer.NativeNumerals ? "settings.numerals.on" : "settings.numerals.off");
            UpdateDeviceInfo();
        }

        private void OnGeometryChanged(GeometryChangedEvent evt)
        {
            UpdateDeviceInfo();
        }

        /// <summary>Rewrites the device line (resolution included); a no-op when nothing changed.</summary>
        public void UpdateDeviceInfo()
        {
            string summary = DeviceSummary();
            // Writing an identical value would still dirty the layout and re-trigger GeometryChangedEvent.
            if (_deviceInfo.text != summary) _deviceInfo.text = summary;
        }

        /// <summary>The device line shown on the screen (and in the test report screenshot).</summary>
        public string DeviceInfoText
        {
            get { return _deviceInfo.text; }
        }

        private void ToggleGenerator()
        {
            _standardGenerator = !_standardGenerator;
            StyledRoot.EnableInClassList(StandardGeneratorClass, _standardGenerator);
            OnRefresh();
        }

        public static string DeviceSummary()
        {
            return string.Format(
                "Unity {0} · {1} · {2} · {3} · {4} MB RAM · {5}x{6} @ {7} dpi · {8}",
                Application.unityVersion,
                SystemInfo.deviceModel,
                SystemInfo.operatingSystem,
                SystemInfo.graphicsDeviceType,
                SystemInfo.systemMemorySize,
                Screen.width,
                Screen.height,
                Mathf.RoundToInt(Screen.dpi),
                Application.version);
        }
    }
}
