// <auto-generated>
// Generated by shared/golden/make_golden.py --enums-cs from shared/enums.json (itself exported from
// pipeline/ghumante_pipeline/model.py). Do not edit by hand: enums are append-only, and
// core-tests/EnumsTests.cs checks every name and value against shared/enums.json.
// </auto-generated>
using System;

namespace Ghumante.Core.Data
{
    public enum RoadClass : byte
    {
        Unknown = 0,
        Motorway = 1,
        Trunk = 2,
        Primary = 3,
        Secondary = 4,
        Tertiary = 5,
        Unclassified = 6,
        Residential = 7,
        LivingStreet = 8,
        Service = 9,
        Track = 10,
        Road = 11,
        Pedestrian = 12,
        Footway = 13,
        Path = 14,
        Steps = 15,
        Cycleway = 16,
        Bridleway = 17,
    }

    public enum Surface : byte
    {
        Unknown = 0,
        Asphalt = 1,
        Concrete = 2,
        Brick = 3,
        Cobble = 4,
        Gravel = 5,
        Compacted = 6,
        Dirt = 7,
        Mud = 8,
        Sand = 9,
        Grass = 10,
        Rock = 11,
        SnowIce = 12,
        Wood = 13,
        Metal = 14,
    }

    public enum SurfaceGroup : byte
    {
        Paved = 0,
        Gravel = 1,
        Dirt = 2,
        Mud = 3,
    }

    public enum SurfaceSource : byte
    {
        Tagged = 0,
        Derived = 1,
        Inferred = 2,
        Default = 3,
    }

    public enum SacScale : byte
    {
        Unknown = 0,
        Hiking = 1,
        MountainHiking = 2,
        DemandingMountainHiking = 3,
        AlpineHiking = 4,
        DemandingAlpineHiking = 5,
        DifficultAlpineHiking = 6,
    }

    public enum BuildingUse : byte
    {
        Unknown = 0,
        House = 1,
        Apartments = 2,
        Commercial = 3,
        MixedUse = 4,
        Education = 5,
        Health = 6,
        Public = 7,
        Industrial = 8,
        Religious = 9,
        Hotel = 10,
        Hut = 11,
        Greenhouse = 12,
        Construction = 13,
        Roof = 14,
        Garage = 15,
        Office = 16,
        Farm = 17,
    }

    public enum BuildingArchetype : byte
    {
        Generic = 0,
        Newar = 1,
        ModernUrban = 2,
        HillVillage = 3,
        Terai = 4,
        SherpaHimalayan = 5,
        TransHimalayan = 6,
        TemplePagoda = 7,
        TempleShikhara = 8,
        Stupa = 9,
        Gompa = 10,
        Chorten = 11,
        Shrine = 12,
        Mosque = 13,
        Church = 14,
        Industrial = 15,
        Institutional = 16,
        Hut = 17,
        Greenhouse = 18,
        Teahouse = 19,
    }

    public enum RoofShape : byte
    {
        Unknown = 0,
        Flat = 1,
        Gabled = 2,
        Hipped = 3,
        Pyramidal = 4,
        Skillion = 5,
        Dome = 6,
        Round = 7,
        Pagoda = 8,
        Shikhara = 9,
        Gambrel = 10,
        Mansard = 11,
        HalfHipped = 12,
        Onion = 13,
        Cone = 14,
    }

    public enum RoofMaterial : byte
    {
        Unknown = 0,
        Concrete = 1,
        Metal = 2,
        Tiles = 3,
        Slate = 4,
        Thatch = 5,
        Wood = 6,
        Glass = 7,
        Mud = 8,
        Stone = 9,
    }

    public enum WallMaterial : byte
    {
        Unknown = 0,
        Plaster = 1,
        Brick = 2,
        Stone = 3,
        Mud = 4,
        Wood = 5,
        Bamboo = 6,
        Metal = 7,
        Glass = 8,
    }

    public enum PlaceKind : byte
    {
        None = 0,
        Country = 1,
        Province = 2,
        City = 3,
        Town = 4,
        Village = 5,
        Hamlet = 6,
        IsolatedDwelling = 7,
        Suburb = 8,
        Neighbourhood = 9,
        Quarter = 10,
        Locality = 11,
        Farm = 12,
        Square = 13,
        Island = 14,
        District = 15,
        LocalLevel = 16,
        Ward = 17,
    }

    public enum PoiKind : ushort
    {
        None = 0,
        TempleHindu = 100,
        Stupa = 101,
        Gompa = 102,
        Shrine = 103,
        Mosque = 104,
        Church = 105,
        PlaceOfWorship = 106,
        Chorten = 107,
        ManiWall = 108,
        HeritageSquare = 120,
        Palace = 121,
        Monument = 122,
        Ruins = 123,
        StoneTap = 124,
        CityGate = 125,
        Museum = 126,
        Peak = 200,
        Viewpoint = 201,
        Waterfall = 202,
        Cave = 203,
        Lake = 204,
        HotSpring = 205,
        Glacier = 206,
        Pass = 207,
        Spring = 208,
        River = 209,
        Park = 210,
        ProtectedArea = 211,
        NotableTree = 212,
        Ridge = 213,
        Airport = 300,
        Helipad = 301,
        BusStation = 302,
        Fuel = 303,
        CableCarStation = 304,
        RailwayStation = 305,
        TaxiStand = 306,
        Bridge = 307,
        Parking = 308,
        Hotel = 400,
        GuestHouse = 401,
        Hostel = 402,
        CampSite = 403,
        Teahouse = 404,
        Restaurant = 405,
        Cafe = 406,
        Attraction = 407,
        Shop = 408,
        Marketplace = 409,
        Information = 410,
        PicnicSite = 411,
        ThemePark = 412,
        Zoo = 413,
        Bungee = 500,
        Paragliding = 501,
        Zipline = 502,
        Rafting = 503,
        Boating = 504,
        Safari = 505,
        School = 600,
        Hospital = 601,
        Government = 602,
        Bank = 603,
    }

    public enum AreaKind : byte
    {
        None = 0,
        WaterLake = 1,
        WaterRiver = 2,
        WaterPond = 3,
        Glacier = 4,
        Wetland = 5,
        Forest = 6,
        Farmland = 7,
        Orchard = 8,
        Meadow = 9,
        Scrub = 10,
        Park = 11,
        Residential = 12,
        Commercial = 13,
        Industrial = 14,
        Religious = 15,
        Pedestrian = 16,
        SandShingle = 17,
        BareRock = 18,
        Aerodrome = 19,
        Cemetery = 20,
        Military = 21,
        Pitch = 22,
        Protected = 23,
        TeaGarden = 24,
        Grassland = 25,
        Scree = 26,
    }

    public enum LineKind : byte
    {
        None = 0,
        River = 1,
        Stream = 2,
        Canal = 3,
        Ditch = 4,
        Railway = 5,
        CableCar = 6,
        ChairLift = 7,
        ZipLine = 8,
        Runway = 9,
        Taxiway = 10,
        CityWall = 11,
        ManiWall = 12,
        Waterfall = 13,
    }

    public enum Biome : byte
    {
        None = 0,
        Water = 1,
        UrbanDense = 2,
        UrbanGreen = 3,
        TeraiPaddy = 4,
        TeraiCropland = 5,
        TeraiSalForest = 6,
        TeraiGrassland = 7,
        RiverbedGravel = 8,
        ChureForest = 9,
        HillTerraces = 10,
        HillForest = 11,
        HillScrub = 12,
        HillGrassland = 13,
        SubalpineForest = 14,
        AlpineMeadow = 15,
        AlpineScrub = 16,
        ScreeRock = 17,
        Moraine = 18,
        Glacier = 19,
        Snow = 20,
        TransHimalayanSteppe = 21,
        TransHimalayanCropland = 22,
        Orchard = 23,
        TeaGarden = 24,
        Wetland = 25,
        ValleyCropland = 26,
        BareSoil = 27,
    }

    public enum WorldCover : byte
    {
        Nodata = 0,
        TreeCover = 10,
        Shrubland = 20,
        Grassland = 30,
        Cropland = 40,
        BuiltUp = 50,
        BareSparse = 60,
        SnowIce = 70,
        PermanentWater = 80,
        HerbaceousWetland = 90,
        Mangroves = 95,
        MossLichen = 100,
    }

    [Flags]
    public enum Travel : byte
    {
        None = 0,
        Foot = 1,
        Bicycle = 2,
        Motorbike = 4,
        Car = 8,
        Jeep = 16,
        Bus = 32,
        Horse = 64,
    }

    [Flags]
    public enum RoadFlags : byte
    {
        None = 0,
        Oneway = 1,
        Bridge = 2,
        Tunnel = 4,
        HasPrevCtx = 8,
        HasNextCtx = 16,
        Link = 32,
        Ford = 64,
        SacInferred = 128,
    }

    [Flags]
    public enum BuildingFlags : byte
    {
        None = 0,
        LevelsInferred = 1,
        HeightTagged = 2,
        RoofTagged = 4,
        Landmark = 8,
        Part = 16,
    }

    [Flags]
    public enum PoiFlags : byte
    {
        None = 0,
        Discoverable = 1,
        Landmark = 2,
        HasEle = 4,
        Sacred = 8,
    }

    /// <summary>Physics family of each surface (model.SURFACE_GROUP).</summary>
    public static class SurfaceGroups
    {
        private static readonly SurfaceGroup[] Table =
        {
            SurfaceGroup.Dirt, // Unknown
            SurfaceGroup.Paved, // Asphalt
            SurfaceGroup.Paved, // Concrete
            SurfaceGroup.Paved, // Brick
            SurfaceGroup.Paved, // Cobble
            SurfaceGroup.Gravel, // Gravel
            SurfaceGroup.Gravel, // Compacted
            SurfaceGroup.Dirt, // Dirt
            SurfaceGroup.Mud, // Mud
            SurfaceGroup.Dirt, // Sand
            SurfaceGroup.Dirt, // Grass
            SurfaceGroup.Gravel, // Rock
            SurfaceGroup.Mud, // SnowIce
            SurfaceGroup.Paved, // Wood
            SurfaceGroup.Paved, // Metal
        };

        /// <summary>The group of a surface; unknown (newer) values count as DIRT, as in routing.py.</summary>
        public static SurfaceGroup Of(Surface s)
        {
            int i = (int)s;
            return i < Table.Length ? Table[i] : SurfaceGroup.Dirt;
        }
    }

    public static class TravelMasks
    {
        /// <summary>Every travel mode (model.ALL_TRAVEL).</summary>
        public const Travel All = (Travel)0x7F;
    }
}
