// <auto-generated>
// Generated by shared/golden/make_golden.py --enums-cs from shared/enums.json (itself exported from
// pipeline/ghumante_pipeline/model.py). Do not edit by hand: enums are append-only, and
// core-tests/EnumsTests.cs checks every name and value against shared/enums.json.
// </auto-generated>
using System;

namespace Ghumante.Core.Data
{
    public enum RoadClass : byte
    {
        Unknown = 0,
        Motorway = 1,
        Trunk = 2,
        Primary = 3,
        Secondary = 4,
        Tertiary = 5,
        Unclassified = 6,
        Residential = 7,
        LivingStreet = 8,
        Service = 9,
        Track = 10,
        Road = 11,
        Pedestrian = 12,
        Footway = 13,
        Path = 14,
        Steps = 15,
        Cycleway = 16,
        Bridleway = 17,
    }

    public enum Surface : byte
    {
        Unknown = 0,
        Asphalt = 1,
        Concrete = 2,
        Brick = 3,
        Cobble = 4,
        Gravel = 5,
        Compacted = 6,
        Dirt = 7,
        Mud = 8,
        Sand = 9,
        Grass = 10,
        Rock = 11,
        SnowIce = 12,
        Wood = 13,
        Metal = 14,
    }

    public enum SurfaceGroup : byte
    {
        Paved = 0,
        Gravel = 1,
        Dirt = 2,
        Mud = 3,
    }

    public enum SurfaceSource : byte
    {
        Tagged = 0,
        Derived = 1,
        Inferred = 2,
        Default = 3,
    }

    public enum SacScale : byte
    {
        Unknown = 0,
        Hiking = 1,
        MountainHiking = 2,
        DemandingMountainHiking = 3,
        AlpineHiking = 4,
        DemandingAlpineHiking = 5,
        DifficultAlpineHiking = 6,
    }

    public enum BuildingUse : byte
    {
        Unknown = 0,
        House = 1,
        Apartments = 2,
        Commercial = 3,
        MixedUse = 4,
        Education = 5,
        Health = 6,
        Public = 7,
        Industrial = 8,
        Religious = 9,
        Hotel = 10,
        Hut = 11,
        Greenhouse = 12,
        Construction = 13,
        Roof = 14,
        Garage = 15,
        Office = 16,
        Farm = 17,
    }

    public enum BuildingArchetype : byte
    {
        Generic = 0,
        Newar = 1,
        ModernUrban = 2,
        HillVillage = 3,
        Terai = 4,
        SherpaHimalayan = 5,
        TransHimalayan = 6,
        TemplePagoda = 7,
        TempleShikhara = 8,
        Stupa = 9,
        Gompa = 10,
        Chorten = 11,
        Shrine = 12,
        Mosque = 13,
        Church = 14,
        Industrial = 15,
        Institutional = 16,
        Hut = 17,
        Greenhouse = 18,
        Teahouse = 19,
        RanaPalace = 20,
        NewarHybrid = 21,
    }

    public enum RoofShape : byte
    {
        Unknown = 0,
        Flat = 1,
        Gabled = 2,
        Hipped = 3,
        Pyramidal = 4,
        Skillion = 5,
        Dome = 6,
        Round = 7,
        Pagoda = 8,
        Shikhara = 9,
        Gambrel = 10,
        Mansard = 11,
        HalfHipped = 12,
        Onion = 13,
        Cone = 14,
    }

    public enum RoofMaterial : byte
    {
        Unknown = 0,
        Concrete = 1,
        Metal = 2,
        Tiles = 3,
        Slate = 4,
        Thatch = 5,
        Wood = 6,
        Glass = 7,
        Mud = 8,
        Stone = 9,
    }

    public enum WallMaterial : byte
    {
        Unknown = 0,
        Plaster = 1,
        Brick = 2,
        Stone = 3,
        Mud = 4,
        Wood = 5,
        Bamboo = 6,
        Metal = 7,
        Glass = 8,
    }

    public enum PlaceKind : byte
    {
        None = 0,
        Country = 1,
        Province = 2,
        City = 3,
        Town = 4,
        Village = 5,
        Hamlet = 6,
        IsolatedDwelling = 7,
        Suburb = 8,
        Neighbourhood = 9,
        Quarter = 10,
        Locality = 11,
        Farm = 12,
        Square = 13,
        Island = 14,
        District = 15,
        LocalLevel = 16,
        Ward = 17,
    }

    public enum PoiKind : ushort
    {
        None = 0,
        TempleHindu = 100,
        Stupa = 101,
        Gompa = 102,
        Shrine = 103,
        Mosque = 104,
        Church = 105,
        PlaceOfWorship = 106,
        Chorten = 107,
        ManiWall = 108,
        HeritageSquare = 120,
        Palace = 121,
        Monument = 122,
        Ruins = 123,
        StoneTap = 124,
        CityGate = 125,
        Museum = 126,
        Peak = 200,
        Viewpoint = 201,
        Waterfall = 202,
        Cave = 203,
        Lake = 204,
        HotSpring = 205,
        Glacier = 206,
        Pass = 207,
        Spring = 208,
        River = 209,
        Park = 210,
        ProtectedArea = 211,
        NotableTree = 212,
        Ridge = 213,
        Airport = 300,
        Helipad = 301,
        BusStation = 302,
        Fuel = 303,
        CableCarStation = 304,
        RailwayStation = 305,
        TaxiStand = 306,
        Bridge = 307,
        Parking = 308,
        Hotel = 400,
        GuestHouse = 401,
        Hostel = 402,
        CampSite = 403,
        Teahouse = 404,
        Restaurant = 405,
        Cafe = 406,
        Attraction = 407,
        Shop = 408,
        Marketplace = 409,
        Information = 410,
        PicnicSite = 411,
        ThemePark = 412,
        Zoo = 413,
        Bungee = 500,
        Paragliding = 501,
        Zipline = 502,
        Rafting = 503,
        Boating = 504,
        Safari = 505,
        School = 600,
        Hospital = 601,
        Government = 602,
        Bank = 603,
        Statue = 127,
        Ghat = 128,
        ParaglidingLanding = 506,
    }

    public enum AreaKind : byte
    {
        None = 0,
        WaterLake = 1,
        WaterRiver = 2,
        WaterPond = 3,
        Glacier = 4,
        Wetland = 5,
        Forest = 6,
        Farmland = 7,
        Orchard = 8,
        Meadow = 9,
        Scrub = 10,
        Park = 11,
        Residential = 12,
        Commercial = 13,
        Industrial = 14,
        Religious = 15,
        Pedestrian = 16,
        SandShingle = 17,
        BareRock = 18,
        Aerodrome = 19,
        Cemetery = 20,
        Military = 21,
        Pitch = 22,
        Protected = 23,
        TeaGarden = 24,
        Grassland = 25,
        Scree = 26,
        Marketplace = 27,
        Parking = 28,
        BusPark = 29,
        Campus = 30,
        Kiln = 31,
        Quarry = 32,
        Stadium = 33,
        Golf = 34,
        Pool = 35,
        Apron = 36,
        PowerPlant = 37,
        Courtyard = 38,
        TrafficIsland = 39,
    }

    public enum LineKind : byte
    {
        None = 0,
        River = 1,
        Stream = 2,
        Canal = 3,
        Ditch = 4,
        Railway = 5,
        CableCar = 6,
        ChairLift = 7,
        ZipLine = 8,
        Runway = 9,
        Taxiway = 10,
        CityWall = 11,
        ManiWall = 12,
        Waterfall = 13,
        TreeRow = 14,
        Cliff = 15,
        GhatEdge = 16,
        PowerLine = 17,
        Wall = 18,
        Fence = 19,
        Hedge = 20,
        RetainingWall = 21,
        Kerb = 22,
        Ferry = 23,
        Dam = 24,
        Weir = 25,
        Penstock = 26,
    }

    public enum Biome : byte
    {
        None = 0,
        Water = 1,
        UrbanDense = 2,
        UrbanGreen = 3,
        TeraiPaddy = 4,
        TeraiCropland = 5,
        TeraiSalForest = 6,
        TeraiGrassland = 7,
        RiverbedGravel = 8,
        ChureForest = 9,
        HillTerraces = 10,
        HillForest = 11,
        HillScrub = 12,
        HillGrassland = 13,
        SubalpineForest = 14,
        AlpineMeadow = 15,
        AlpineScrub = 16,
        ScreeRock = 17,
        Moraine = 18,
        Glacier = 19,
        Snow = 20,
        TransHimalayanSteppe = 21,
        TransHimalayanCropland = 22,
        Orchard = 23,
        TeaGarden = 24,
        Wetland = 25,
        ValleyCropland = 26,
        BareSoil = 27,
    }

    public enum WorldCover : byte
    {
        Nodata = 0,
        TreeCover = 10,
        Shrubland = 20,
        Grassland = 30,
        Cropland = 40,
        BuiltUp = 50,
        BareSparse = 60,
        SnowIce = 70,
        PermanentWater = 80,
        HerbaceousWetland = 90,
        Mangroves = 95,
        MossLichen = 100,
    }

    [Flags]
    public enum Travel : byte
    {
        None = 0,
        Foot = 1,
        Bicycle = 2,
        Motorbike = 4,
        Car = 8,
        Jeep = 16,
        Bus = 32,
        Horse = 64,
    }

    [Flags]
    public enum RoadFlags : byte
    {
        None = 0,
        Oneway = 1,
        Bridge = 2,
        Tunnel = 4,
        HasPrevCtx = 8,
        HasNextCtx = 16,
        Link = 32,
        Ford = 64,
        SacInferred = 128,
    }

    [Flags]
    public enum BuildingFlags : byte
    {
        None = 0,
        LevelsInferred = 1,
        HeightTagged = 2,
        RoofTagged = 4,
        Landmark = 8,
        Part = 16,
        HasParts = 32,
        TagSuspect = 64,
        OpenCanopy = 128,
    }

    [Flags]
    public enum PoiFlags : byte
    {
        None = 0,
        Discoverable = 1,
        Landmark = 2,
        HasEle = 4,
        Sacred = 8,
        HasFootprint = 16,
        LandmarkLite = 32,
        Inferred = 64,
    }

    public enum StyleProfile : byte
    {
        None = 0,
        KathmanduCore = 1,
        Thamel = 2,
        Patan = 3,
        Bhaktapur = 4,
        Kirtipur = 5,
        Thimi = 6,
        Bungamati = 7,
        Khokana = 8,
        Panauti = 9,
        Metro = 10,
        Rim = 11,
        BoudhaKora = 12,
    }

    public enum AreaType : byte
    {
        Unknown = 0,
        OldCore = 1,
        Urban = 2,
        PeriUrban = 3,
        Rural = 4,
        Hill = 5,
        Forest = 6,
    }

    public enum JunctionKind : byte
    {
        Plain = 0,
        Roundabout = 1,
        Circular = 2,
        MiniRoundabout = 3,
        Signals = 4,
        Police = 5,
        SyntheticIsland = 6,
    }

    public enum Sidewalk : byte
    {
        Unknown = 0,
        None = 1,
        Left = 2,
        Right = 3,
        Both = 4,
        Separate = 5,
    }

    public enum ObjectKind : byte
    {
        None = 0,
        Tree = 1,
        PowerTower = 2,
        PowerPole = 3,
        StreetLamp = 4,
        BusStop = 5,
        Shelter = 6,
        Bench = 7,
        WaterTap = 8,
        Well = 9,
        Gate = 10,
        Chimney = 11,
        Mast = 12,
        Tower = 13,
        StorageTank = 14,
        SolarPanel = 15,
        Artwork = 16,
        TrafficSignals = 17,
        CrossingMarked = 18,
        CrossingUnmarked = 19,
        AerowayGate = 20,
        ParkingPosition = 21,
        Windsock = 22,
        Helipad = 23,
        TaxiStand = 24,
    }

    public enum TreeClass : byte
    {
        Unknown = 0,
        Pipal = 1,
        Bar = 2,
        Broadleaf = 3,
        Conifer = 4,
        Palm = 5,
    }

    public enum TransitMode : byte
    {
        None = 0,
        Bus = 1,
        Microbus = 2,
        Tempo = 3,
        ShareTaxi = 4,
        Hiking = 5,
        Foot = 6,
        Bicycle = 7,
        Mtb = 8,
    }

    public enum LiveryClass : byte
    {
        None = 0,
        CityGreen = 1,
        Minibus = 2,
        Microbus = 3,
        SafaTempo = 4,
        Coach = 5,
    }

    public enum TurnRestriction : byte
    {
        None = 0,
        NoLeftTurn = 1,
        NoRightTurn = 2,
        NoStraightOn = 3,
        NoUTurn = 4,
        OnlyLeftTurn = 5,
        OnlyRightTurn = 6,
        OnlyStraightOn = 7,
        NoEntry = 8,
        NoExit = 9,
    }

    public enum HeritageKind : byte
    {
        None = 0,
        Pagoda = 1,
        ShikharaStone = 2,
        ShikharaPlaster = 3,
        Stupa = 4,
        HouseTemple = 5,
        Mandapa = 6,
        Relief = 7,
        Column = 8,
        Gate = 9,
        Palace = 10,
        Tower = 11,
        Hiti = 12,
        Pokhari = 13,
        Gompa = 14,
        Bahal = 15,
    }

    public enum HeritageFinish : byte
    {
        Unknown = 0,
        Tile = 1,
        GiltTop = 2,
        GiltAll = 3,
        Whitewash = 4,
        Stone = 5,
        Brick = 6,
        Stucco = 7,
        Terracotta = 8,
    }

    public enum EntryRule : byte
    {
        None = 0,
        ShoesOff = 1,
        QuietWorship = 2,
        RealCompoundClosedToNonHindus = 3,
        InteriorNoPhoto = 4,
        KumariNotShown = 5,
        NoLeather = 6,
    }

    public enum KoraDirection : byte
    {
        None = 0,
        Clockwise = 1,
        Anticlockwise = 2,
    }

    public enum SacredZoneKind : byte
    {
        None = 0,
        Compound = 1,
        Courtyard = 2,
        HeritageSquare = 3,
        StupaKora = 4,
        Ghat = 5,
    }

    [Flags]
    public enum RoadAttrFlags : byte
    {
        None = 0,
        Dual = 1,
        ServiceRoad = 2,
        HeritagePedestrian = 4,
        NoMotor = 8,
        Lit = 16,
        BusRoute = 32,
        RingMember = 64,
        Paintable = 128,
    }

    [Flags]
    public enum JunctionFlags : byte
    {
        None = 0,
        HasIslandArea = 1,
        Officers24 = 2,
        HeritageNoMotor = 4,
        CrossingsMarked = 8,
        HasPolice = 16,
        HasSignals = 32,
    }

    [Flags]
    public enum BuildingFrontFlags : byte
    {
        None = 0,
        CourtyardHost = 1,
        Corner = 2,
        FacesHeritageSquare = 4,
        RanaHint = 8,
        StructureRcc = 16,
        StructureMud = 32,
        RoofFlatTagged = 64,
        TrimmedForRoad = 128,
    }

    [Flags]
    public enum PropFlags : byte
    {
        None = 0,
        Yaw = 1,
        HeightTagged = 2,
        Chautari = 4,
        FromWay = 8,
        OnRoad = 16,
    }

    [Flags]
    public enum RouteFlags : byte
    {
        None = 0,
        Roundtrip = 1,
        StopsFromMembers = 2,
        StopsInferred = 4,
        HasGaps = 8,
        MissingWays = 16,
    }

    [Flags]
    public enum StopFlags : byte
    {
        None = 0,
        FromMember = 1,
        Inferred = 2,
        Terminal = 4,
    }

    [Flags]
    public enum HeritageFlags : byte
    {
        None = 0,
        ManualPosition = 1,
        HasCompound = 2,
        WalkableCompound = 4,
        NoVehicles = 8,
        SanctumClosed = 16,
        Verify = 32,
    }

    public enum RoadStructureKind : byte
    {
        None = 0,
        Bridge = 1,
        Flyover = 2,
        Underpass = 3,
        Tunnel = 4,
        Ford = 5,
    }

    [Flags]
    public enum RoadStructureFlags : byte
    {
        None = 0,
        CarAccessible = 1,
        WaterCrossing = 2,
        DeckFromTags = 4,
        FootOverbridge = 8,
        Lowered = 16,
        Approach = 32,
        Squeezed = 64,
        OverRoad = 128,
    }

    /// <summary>Physics family of each surface (model.SURFACE_GROUP).</summary>
    public static class SurfaceGroups
    {
        private static readonly SurfaceGroup[] Table =
        {
            SurfaceGroup.Dirt, // Unknown
            SurfaceGroup.Paved, // Asphalt
            SurfaceGroup.Paved, // Concrete
            SurfaceGroup.Paved, // Brick
            SurfaceGroup.Paved, // Cobble
            SurfaceGroup.Gravel, // Gravel
            SurfaceGroup.Gravel, // Compacted
            SurfaceGroup.Dirt, // Dirt
            SurfaceGroup.Mud, // Mud
            SurfaceGroup.Dirt, // Sand
            SurfaceGroup.Dirt, // Grass
            SurfaceGroup.Gravel, // Rock
            SurfaceGroup.Mud, // SnowIce
            SurfaceGroup.Paved, // Wood
            SurfaceGroup.Paved, // Metal
        };

        /// <summary>The group of a surface; unknown (newer) values count as DIRT, as in routing.py.</summary>
        public static SurfaceGroup Of(Surface s)
        {
            int i = (int)s;
            return i < Table.Length ? Table[i] : SurfaceGroup.Dirt;
        }
    }

    public static class TravelMasks
    {
        /// <summary>Every travel mode (model.ALL_TRAVEL).</summary>
        public const Travel All = (Travel)0x7F;
    }
}
