using System;
using System.Threading;
using System.Threading.Tasks;
using Ghumante.Core.Meshing;
using Ghumante.Core.Synth.Textures;
using UnityEngine;

namespace Ghumante.World.Rendering
{
    /// <summary>
    /// The runtime texture array of the cartoon look: every <see cref="MaterialChannel"/> texture is generated by
    /// <see cref="MaterialTextures"/> on worker threads (nothing is stored in the build), then uploaded on the main thread
    /// as one mipmapped sRGB <see cref="Texture2DArray"/> (slice = channel) and bound globally as <c>_GhMaterialTex</c>.
    /// Until the bake is done a 4 × 4 neutral array is bound, which renders exactly the flat vertex colours.
    /// Memory: 26 slices × 256² × 4 B × 4/3 ≈ 9 MB (Low, 128²: ≈ 2.3 MB). Bake time ≈ 0.3 s of worker time per
    /// core on a phone at 256².
    /// </summary>
    public sealed class ToonTextureBank : IDisposable
    {
        public static readonly int MaterialTexId = Shader.PropertyToID("_GhMaterialTex");

        private const string ArrayName = "Ghumante Material Textures";
        private const string NeutralName = "Ghumante Material Textures (neutral)";

        // Arrays owned by banks of this domain (a domain reload empties it; whatever it does not list is a leftover).
        private static readonly System.Collections.Generic.List<Texture2DArray> Live = new System.Collections.Generic.List<Texture2DArray>();

        private readonly int _size;
        private byte[][][] _baked;          // [slice][mip] RGBA8 sRGB, set by the worker
        private int _state;                 // 0 idle, 1 baking, 2 baked, 3 uploaded, 4 failed
        private Texture2DArray _array;
        private Texture2DArray _placeholder;
        private string _error;

        /// <summary>A bank for textures of <paramref name="size"/> texels (power of two, 8..2048).</summary>
        public ToonTextureBank(int size)
        {
            if (!MaterialTextures.IsValidSize(size)) throw new ArgumentOutOfRangeException(nameof(size));
            _size = size;
        }

        /// <summary>Edge length of the textures.</summary>
        public int Size
        {
            get { return _size; }
        }

        /// <summary>The uploaded array, or null while baking.</summary>
        public Texture2DArray Array
        {
            get { return _array; }
        }

        /// <summary>True once the real textures are bound.</summary>
        public bool IsUploaded
        {
            get { return Volatile.Read(ref _state) == 3; }
        }

        /// <summary>Binds the neutral placeholder and starts the bake on the thread pool (once).</summary>
        public void Start()
        {
            // The editor keeps DontSave textures across domain reloads, while the bank that owned them is gone.
            if (_placeholder == null && Application.isEditor) DestroyLeftovers();
            if (_placeholder == null)
            {
                _placeholder = Neutral();
                Live.Add(_placeholder);
                Shader.SetGlobalTexture(MaterialTexId, _placeholder);
            }
            if (Interlocked.CompareExchange(ref _state, 1, 0) != 0) return;
            int size = _size;
            Task.Run(() =>
            {
                try
                {
                    int slices = MaterialTextures.SliceCount;
                    var baked = new byte[slices][][];
                    Parallel.For(0, slices, s => { baked[s] = MaterialTextures.Bake((MaterialChannel)s, size); });
                    _baked = baked;
                    Volatile.Write(ref _state, 2);
                }
                catch (Exception e)
                {
                    _error = e.ToString();
                    Volatile.Write(ref _state, 4);
                }
            });
        }

        /// <summary>
        /// Main thread: uploads the baked textures when the worker is done and binds them (one frame of about 9 MB of
        /// copies, at startup). Returns true when the real textures are bound. Cheap to call every frame.
        /// </summary>
        public bool TryUpload(int anisoLevel)
        {
            int state = Volatile.Read(ref _state);
            if (state == 3) return true;
            if (state == 4)
            {
                Debug.LogError("ToonTextureBank: material texture bake failed; the world keeps flat colours.\n" + _error);
                Volatile.Write(ref _state, 5);
                return false;
            }
            if (state != 2) return false;
            byte[][][] baked = _baked;
            int slices = baked.Length, mips = baked[0].Length;
            var array = new Texture2DArray(_size, _size, slices, TextureFormat.RGBA32, true, false)
            {
                name = ArrayName,
                filterMode = FilterMode.Trilinear,
                wrapMode = TextureWrapMode.Repeat,
                anisoLevel = anisoLevel,
                hideFlags = HideFlags.DontSave,
            };
            for (int s = 0; s < slices; s++)
                for (int m = 0; m < mips; m++)
                    array.SetPixelData(baked[s][m], m, s);
            array.Apply(false, true);
            _array = array;
            Live.Add(array);
            _baked = null;
            Shader.SetGlobalTexture(MaterialTexId, array);
            Volatile.Write(ref _state, 3);
            return true;
        }

        /// <summary>Sets the anisotropic filtering of the uploaded array.</summary>
        public void SetAniso(int anisoLevel)
        {
            if (_array != null && _array.anisoLevel != anisoLevel) _array.anisoLevel = anisoLevel;
        }

        /// <summary>Destroys the textures (the global binding is left to the next bank).</summary>
        public void Dispose()
        {
            Live.Remove(_array);
            Live.Remove(_placeholder);
            Destroy(_array);
            Destroy(_placeholder);
            _array = null;
            _placeholder = null;
            _baked = null;
        }

        private static void Destroy(UnityEngine.Object o)
        {
            if (o == null) return;
            if (Application.isPlaying) UnityEngine.Object.Destroy(o);
            else UnityEngine.Object.DestroyImmediate(o);
        }

        private static void DestroyLeftovers()
        {
            Texture2DArray[] all = Resources.FindObjectsOfTypeAll<Texture2DArray>();
            for (int i = 0; i < all.Length; i++)
            {
                Texture2DArray t = all[i];
                if (t != null && (t.name == ArrayName || t.name == NeutralName) && !Live.Contains(t)) Destroy(t);
            }
        }

        /// <summary>A 4 × 4 single-slice array of the neutral texel (rgb 0.5 linear, tint weight 1): the flat look.</summary>
        private static Texture2DArray Neutral()
        {
            var t = new Texture2DArray(4, 4, 1, TextureFormat.RGBA32, false, false)
            {
                name = NeutralName,
                filterMode = FilterMode.Bilinear,
                wrapMode = TextureWrapMode.Repeat,
                hideFlags = HideFlags.DontSave,
            };
            var px = new byte[4 * 4 * 4];
            for (int i = 0; i < px.Length; i += 4)
            {
                px[i] = px[i + 1] = px[i + 2] = 188; // sRGB 188 = linear 0.5
                px[i + 3] = 255;
            }
            t.SetPixelData(px, 0, 0);
            t.Apply(false, true);
            return t;
        }
    }
}
